[WIP - DO NOT MERGE] Added installation instructions to README.md.
fusor/ansible-playbook-bundle pull request #14
Opened 2017-05-10 20:50 UTC by cfchase

Added installation instructions to README.md
Added first commit of getting_started.md

2017-05-11 01:32 UTC, jmrodri requested changes

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +An **Ansible Playbook Bundle (APB)** is a lightweight application definition (meta-container). They are used to define and deploy complex groups of applications, deployment configs, deployments, and
extra space between 'and simple'.

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +An **Ansible Playbook Bundle (APB)** is a lightweight application definition (meta-container). They are used to define and deploy complex groups of applications, deployment configs, deployments, and
change 'power of Ansible' to be a link to ansible `power of [Ansible](http://www.ansible.com)`

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +* Actions under a directory with named "playbooks" and metadata defined in "apb.yml".
I would format the words in quotes with either *italics*, **bold** or **_both_**.

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +```
What does this do?

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +```
I'm much more partial to using tito to install :)
```
tito build --rpm -i
```

Or make it:

##### Installing from source
Clone this repo
```bash
git clone https://github.com/fusor/ansible-playbook-bundle.git
```
Install requirements and run the setup script (requires python)
```bash
sudo pip install -r src/requirements.txt && sudo python setup.py install
```
Alternatively you can use [tito](http://github.com/dgoodwin/tito) to install.
```bash
tito build --test --rpm -i
```

2017-05-11 01:32 UTC, jmrodri commented on README.md
> +<a name="docs"></a>
I thought markdown creates the links automagically.

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +## Introduction Ansible Playbook Bundles (APBs)
Introduction to Ansible PlaybookBundles (APBs)?

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +In this tutorial, we'll walk through the creation of a APB for a PostgreSQL Database.  You will be able to provision, deprovision, and bind or unbind it to other applications.  You can find more info
an APB?

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +In this tutorial, we'll walk through the creation of a APB for a PostgreSQL Database.  You will be able to provision, deprovision, and bind or unbind it to other applications.  You can find more info
database instead of Database.

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Install APB tooling as documented in the main [README](https://github.com/cfchase/ansible-playbook-bundle/tree/docs#install)
I'd remove main. '... in the [README]'

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Install APB tooling as documented in the main [README](https://github.com/cfchase/ansible-playbook-bundle/tree/docs#install)
The link says cfchase.

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Create a local development environment with both a [Service Catalog](https://github.com/kubernetes-incubator/service-catalog) and [Ansible Service Broker](https://github.com/fusor/ansible-service-bro
This paragraph looks good.

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +docker build -t <docker-user>/hello-world-apb .
Will this be replaced with apb build?

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +This should have deployed a hello-world-apb application to your openshift cluster.  Logging on to your cluster at https://<catasb-host>:<port>, you should be able to view the project and click on the
Let's think more positive, 'This should have deployed...' change to 'This will have deployed ...'

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +This should have deployed a hello-world-apb application to your openshift cluster.  Logging on to your cluster at https://<catasb-host>:<port>, you should be able to view the project and click on the
Change 'should be able' to 'will be able'

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +At this point you should see the following file structure
'should see' to 'will see'

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Two files were created at the root directory.  An apb.yml and a Dockerfile.  These are the minimum required for any APB.  For more information, visit the [design doc](https://github.com/fusor/ansible
apb.yml to `apb.yml` and Dockerfile to `Dockerfile`.

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Visiting the OpenShift console UI at https://<catasb-host>:<port> will now display the new Ansible Playbook bundle named pg-apb in the catalog under the "All" tab.
Good, in this sentence you used 'will now' which is what I want. :+1:

2017-05-11 01:32 UTC, jmrodri commented on docs/getting_started.md
> +Unfortunately, the brand new APB created in the last section doesn't do very much.  For that, we'll have to add some actions.  The actions supported are [provision](#provision), [deprovision](#deprov
I'd remove 'Unfortunately'. The brand new APB, created in the last section, doesn't do very much.

2017-05-11 01:42 UTC, rthallisey commented on README.md
> +An **Ansible Playbook Bundle (APB)** is a lightweight application definition (meta-container). They are used to define and deploy complex groups of applications, deployment configs, deployments, and
This is probably a larger discussion, but should we target kubernetes too? We don't need to have the discussion here, but I think mentioning it as a supported cluster alongside origin is important.

2017-05-11 14:10 UTC, cfchase commented on docs/getting_started.md
> +docker build -t <docker-user>/hello-world-apb .
yes

2017-05-17 17:31 UTC, cfchase commented
Reviewers can click on the "View file" button to actually see the formatted pages.

2017-05-17 17:38 UTC, cfchase commented
@jmrodri I think I addressed your concerns.  I've added another commit to add instructions for provision.

2017-05-17 17:58 UTC, johnkim76 commented
ACK
This looks good to me, and it appears that all the change requests that @jmrodri requested was addressed

2017-05-17 18:32 UTC, jmrodri requested changes
minor nits. Fix those up. Then I'll approve and merge.

2017-05-17 18:32 UTC, jmrodri commented on README.md
> +* Developer Tooling to drive a guided approach.
Make 'Tooling' just 'tooling'.

2017-05-17 18:32 UTC, jmrodri commented on README.md
> +Install using dnf/yum
These two lines get rammed together in the formatted version.

```
Download from [here](????)
￼ Install using dnf/yum
```

2017-05-17 18:32 UTC, jmrodri commented on README.md
> +```
:heart:

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +In this tutorial we'll create an APB for a containerized [hello world application](https://hub.docker.com/r/ansibleplaybookbundle/hello-world/).  We'll work through a basic APB that will mirror the [
add comma (,) after *tutorial*

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +docker build -t <docker-org>/hello-world-apb .
Should this be `apb build`? you mention `apb build` later in the document.

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +Visiting the OpenShift console UI at https://<catasb-host>:<port> will now display the new Ansible Playbook bundle named my-apb in the catalog under the **_All_** tab.
`s/bundle/Bundle` to be consistent with the rest of the document.

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +First, create a new file called main.yml inside a roles/provision-my-apb directory.
add tick marks around yml and directory:
`main.yml` and `roles/provision-my-apb`.

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +Rebuilding the APB (`apb build ...`)and running the provision command (`docker run ...`) should output the output from the Ansible playbook with no changes:
space after the ) of apb build

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +You can click on the new service under **_Networking_** in the application on the overview page or under Applications -> Services.  The services's IP address will be shown which you can use to access
I'd probably make the menu choice italic. _Applications -> Services_

2017-05-17 18:32 UTC, jmrodri commented on docs/getting_started.md
> +You can click on the new service under **_Networking_** in the application on the overview page or under Applications -> Services.  The services's IP address will be shown which you can use to access
should it be services' or service's?

2017-05-17 19:13 UTC, cfchase commented
@jmrodri made changes as per your comments

2017-05-17 20:31 UTC, jmrodri approved these changes

2017-05-17 20:31 UTC, jmrodri commented
ACK

2017-05-17 20:32 UTC, merged