Added downstream namespace check for getting broker route
fusor/ansible-playbook-bundle pull request #183
Opened 2017-12-21 21:29 UTC by dymurray

2018-01-03 14:30 UTC, rthallisey requested changes

2018-01-03 14:30 UTC, rthallisey commented on src/apb/engine.py
> +            print("Didn't find OAB route in namespace: ansible-service-broker. Trying openshift-ansible-service-broker")
What does OAB stand for?

2018-01-03 14:30 UTC, rthallisey commented on src/apb/engine.py
> +            route_list = oapi.list_namespaced_route('hift-ansible-service-broker')
```hift-ansible-service-broker``` -> ```openshift-ansible-service-broker```

2018-01-03 14:34 UTC, cfchase approved these changes
ACK

2018-01-05 18:46 UTC, djzager approved these changes
ACK

2018-01-05 19:04 UTC, rthallisey approved these changes

2018-01-05 19:04 UTC, merged