Bug 1537599 - Push when running apb test.
fusor/ansible-playbook-bundle pull request #226
Opened 2018-02-07 18:34 UTC by cfchase

2018-02-07 18:41 UTC, djzager reviewed
LGTM. Finishing up something else and I'll test and approve. What's a good example apb to use?

2018-02-07 18:56 UTC, cfchase commented
@djzager this is what I was using.  feel free to play with it.  https://github.com/cfchase/test-apb

2018-02-07 20:04 UTC, djzager requested changes
Just need to set the tag based on the registry before you build it in order for it to work correctly. After that I believe this will be ready.

2018-02-07 20:04 UTC, djzager commented on src/apb/engine.py
> +    registry = get_registry(kwargs)
If you have a look at the `cmdrun_run` you'll see we set the tag based on the registry like:

```
    apb_project = kwargs['base_path']
    registry = get_registry(kwargs)
    spec = get_spec(apb_project)
    tag = registry + "/" + kwargs['namespace'] + "/" + spec['name']

    image = build_apb(
        apb_project,
        kwargs['dockerfile'],
        tag
    )
    push_apb(registry, tag)
```

I think you will need to do something like that in order for this to work correctly.

2018-02-07 20:58 UTC, djzager commented on src/apb/cli.py
>          dest='dockerfile',
While you are at it, if you could remove the `tag` argument please.

2018-02-12 15:42 UTC, djzager approved these changes
ACK

2018-02-12 15:44 UTC, dymurray approved these changes

2018-02-12 15:45 UTC, eriknelson requested changes
I don't think this takes minishift  into account, but I'm not positive since you might be using the same functions a regular push does. Can you double check?

2018-02-12 15:50 UTC, dymurray commented
@eriknelson I think it does actually. The minishift logic is handled in this function: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/a2a180a85f7e387362214a65097efa4550724a77/src/apb/engine.py#L1338

`build_apb` and `push_apb` both call this function when building and pushing. @djzager am I right in that?

2018-02-12 15:55 UTC, eriknelson approved these changes

2018-02-12 15:56 UTC, eriknelson commented
Confirmed it does use the shared logic. Thanks @dymurray, the other one I was concerned about was the tag, but that's also hidden behind `get_registry`. It's important that the internal minishift registry ip gets used when tagging images, if you're pushing to minishift.

2018-02-12 16:22 UTC, merged