Add a command to refresh all the catalog data
fusor/ansible-playbook-bundle pull request #259
Opened 2018-04-06 13:46 UTC by rthallisey

This should help mitigate the issue where the catalog is holding old data.

2018-04-06 16:20 UTC, djzager requested changes
This should be helpful. Looks good, just a few comments.

2018-04-06 16:20 UTC, djzager commented on src/apb/engine.py
> +    print "Catalog data has be removed. Relisting data.."
been removed.

2018-04-06 16:20 UTC, djzager commented on src/apb/engine.py
> +    delete_classes = "oc get clusterserviceclass --no-headers | awk '{ print $1 }'"
Can you use `kubectl` instead? I know that we must shell out since these aren't supported in the openshift/k8s client but  since we don't know how long this version of the apb tool will last it would be nice to at least attempt to be agnostic.

2018-04-06 16:20 UTC, djzager commented on src/apb/engine.py
> +    delete_classes = "oc get clusterserviceclass --no-headers | awk '{ print $1 }'"
Same for the others below.

2018-04-09 14:13 UTC, dymurray approved these changes
LGTM

2018-04-09 20:10 UTC, djzager approved these changes
ACK

2018-04-09 22:13 UTC, merged