Fix links to ASB
fusor/ansible-playbook-bundle pull request #262
Opened 2018-04-12 08:51 UTC by SaravanaStorageNetwork

Fix links to ASB github repo.

2018-04-12 11:23 UTC, djzager approved these changes
ACK. Thanks for the contribution.

2018-04-12 13:26 UTC, shawn-hurley requested changes

2018-04-12 13:26 UTC, shawn-hurley commented on docs/getting_started.md
> +First, make sure your system is properly running [OpenShift Origin](https://www.openshift.org/).  You should be running both the service catalog and Ansible Service Broker (ASB). Instructions can be
I would add a space between Kubernetes and the link. ex 
`Kubernetes [getting started doc]`. Same with openshift and it's link

2018-04-13 06:23 UTC, SaravanaStorageNetwork commented on docs/getting_started.md
> +First, make sure your system is properly running [OpenShift Origin](https://www.openshift.org/).  You should be running both the service catalog and Ansible Service Broker (ASB). Instructions can be
@shawn-hurley  done

2018-04-13 19:30 UTC, shawn-hurley approved these changes

2018-04-13 19:47 UTC, merged