Bug 1526147 - Add instructions for alternative to apb run
fusor/ansible-playbook-bundle pull request #278
Opened 2018-05-01 17:11 UTC by dymurray

2018-05-01 17:24 UTC, djzager requested changes
I think you may need to add a little bit more in the case the APB wants to do anything in the target namespace.

2018-05-01 17:24 UTC, djzager commented on docs/developers.md
> +$ oc run --image 172.30.1.1:5000/openshift/<bundle_name> provision-<bundle_name> provision
It is my understanding that if you want the APB to have sufficient permissions to do anything in the target namespace, you will need to create a serviceaccount and (cluster)rolebinding first. Then pass that serviceaccount to the `oc run` command. By default, the service account given to the pod can't create anything (or even list).

2018-05-01 17:25 UTC, djzager commented on docs/developers.md
> +$ oc run --image 172.30.1.1:5000/openshift/<bundle_name> provision-<bundle_name> provision
This is from the apb-test-shim...may be useful to you.

```
    oc run "$pod_name" \
        --namespace=$apb_name \
        --env="POD_NAME=$pod_name" \
        --env="POD_NAMESPACE=$apb_name" \
        --image=$apb_name \
        --image-pull-policy=Never \
        --restart=Never \
        --attach=true \
        --serviceaccount=$apb_name \
        -- $action -e namespace=$apb_name -e cluster=$CLUSTER
```

2018-05-01 17:45 UTC, dymurray commented on docs/developers.md
> +$ oc run --image 172.30.1.1:5000/openshift/<bundle_name> provision-<bundle_name> provision
Ahh... my test APB just did a debug :) didn't think about that. Thanks!

2018-05-01 18:31 UTC, djzager approved these changes
ACK

2018-05-01 18:31 UTC, merged

2018-05-03 01:40 UTC, jianzhangbjz commented on docs/developers.md
> +$ oc get images | grep <bundle_name>
@dymurray As I described in bug [1541903](https://bugzilla.redhat.com/show_bug.cgi?id=1541903), I could NOT get the pushed image by querying the `bundle_name`, I think we should modify this command, or am I missing something?