Added instructions for bind
fusor/ansible-playbook-bundle pull request #39
Opened 2017-05-24 20:26 UTC by cfchase

2017-05-25 11:45 UTC, rthallisey requested changes
👍 nice doc

2017-05-25 11:45 UTC, rthallisey commented on docs/getting_started.md
> +# MAINTAINER {{ $MAINTAINER }}
Let's set this to ```MAINTAINER ansibleplaybookbundle community```

2017-05-25 11:45 UTC, rthallisey commented on docs/getting_started.md
> +# playbooks/provision.yml
do we need this comment?

2017-05-25 11:45 UTC, rthallisey commented on docs/getting_started.md
> +```yaml
```oc delete pv <my_pv>```

2017-05-25 11:45 UTC, rthallisey commented on docs/getting_started.md
> +    msg: "<BIND_CREDENTIALS>{{ encoded_bind_credentials.stdout }}</BIND_CREDENTIALS>"```
The broker bind output is changing per https://github.com/fusor/apb-examples/pull/25.  So this code will change to https://github.com/fusor/apb-examples/pull/25/commits/f56c0a6bdad4c87fb3a89247c138b874f3974de8

2017-05-25 19:11 UTC, cfchase commented on docs/getting_started.md
> +# MAINTAINER {{ $MAINTAINER }}
This is just a paste showing what `apb init` is generating.  I'd rather not change it, and it was just extra info if I make the user change it.

2017-05-25 19:39 UTC, cfchase commented
@rthallisey I think I've addressed most of your comments.  I can remove the `# MAINTAINER` comment in the Dockerfile if you think that makes more sense.

2017-05-31 17:13 UTC, djwhatle commented
Just attempted running catasb using these instructions and found the following undocumented steps for setup on Fedora 25.

- Create `/etc/docker/daemon.json` to specify the IP of my DNS server, since Google DNS (8.8.8.8, the Docker default) is blocked on my network.


```
$ sudo vi  /etc/docker/daemon.json
```
```
{                                                                               
    "dns": ["X.X.X.X"]                                                       
}  
```

- Give user account sudo-less access to the Docker socket.

```
$ sudo groupadd docker
$ sudo chown root:docker /var/run/docker.sock
$ sudo usermod -aG docker dwhatley
```

 - Add the OpenShift registry as insecure registry to `/etc/sysconfig/docker`, restart docker daemon.
```
$ sudo vi  /etc/sysconfig/docker
```
```
...  
# INSECURE_REGISTRY='--insecure-registry'                                       
INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'  
...
```

```
$ sudo systemctl restart docker
```

2017-05-31 17:44 UTC, rthallisey commented
LGTM.  I think the maintainer comment can be fixed from the apb tool side then we can come back and change it.

2017-05-31 19:31 UTC, jmrodri commented
@djwhatle I didn't have to do anything with daemon.json on either of my machines.

I did have to add myself to the docker group, but didn't have to chmod any socket. I just did a `dnf install docker`

Then I followed the OC instructions to use `oc cluster up`.

https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

2017-05-31 19:33 UTC, jmrodri commented
I would maybe add a prerequisite that you have to have docker and oc installed and setup. Then maybe a troubleshooting section somewhere where it lists out things we did to solve common problems. So adding daemon.json if you can't access dns, etc. But I think it might be different for different machine and could clutter this document which is focused on apbs.

2017-06-01 13:48 UTC, cfchase commented
@jmrodri @djwhatle added a note about installing docker and OpenShift Origin. https://github.com/fusor/ansible-playbook-bundle/pull/39/commits/d022e90f2ac1b2f7b6560f4b98fd4383227e21ad

@rthallisey sounds good, I'll merge after you clear the change request.  I took the maintainer line out in https://github.com/fusor/ansible-playbook-bundle/pull/40 and we can replace it with something that makes more sense when we decide what that is.  Maybe using the --org value since the user has to enter that.

2017-06-01 17:11 UTC, merged