update docs/developers.md to reflect the new parameter changes
fusor/ansible-playbook-bundle pull request #60
Opened 2017-06-23 20:25 UTC by johnkim76

2017-06-23 20:26 UTC, johnkim76 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document new parameter schema way of handling parameters in the ansible playbook bundle. This is for APB developers.](https://trello.com/c/nzDFvGrN/290-document-new-parameter-schema-way-of-handling-parameters-in-the-ansible-playbook-bundle-this-is-for-apb-developers)

2017-06-26 11:54 UTC, rthallisey requested changes

2017-06-26 11:54 UTC, rthallisey commented on docs/developers.md
> +To define variables, use the `main.yml` file under the `defaults` folder to define/set other variables for your APB.  For example, below is the [defualts/main.yml](https://github.com/fusor/apb-exampl
s/```[defualts/main.yaml]```/```[defaults/main.yaml]```/

2017-06-26 11:54 UTC, rthallisey commented on docs/developers.md
> +The above expects the `namespace` variables to be defined, which was not part of the `parameters` in the spec file `apb.yml`.
s/variables/variable/

2017-07-07 16:50 UTC, johnkim76 commented
@rthallisey I've made the changes and squashed

2017-07-07 17:02 UTC, rthallisey approved these changes

2017-07-07 17:05 UTC, merged