Update apb command to latest status in README
fusor/ansible-playbook-bundle pull request #64
Opened 2017-07-06 12:59 UTC by mdshuai

apb command have changed, need update README.

some parameter also not support, like:
```
(apb) [root@dhcp-140-98 dma]# apb init my_apb -p name=my_apb_param,type=string,default=foo_param,description="sample description" --async=optional --bindable --organization my_organization
usage: apb [-h] [--debug] [--project BASE_PATH]
           {init,help,prepare,push,bootstrap,list,remove,build} ...
apb: error: unrecognized arguments: --organization my_organization
```

2017-07-06 13:06 UTC, leifmadsen commented on README.md
> +parameters:
Trailing whitespace? (sorry, not trying to nitpick too much :))

2017-07-06 13:19 UTC, rthallisey requested changes

2017-07-06 13:19 UTC, rthallisey commented on README.md
> +parameters:
This should be ```parameters: []```. The README in apb-examples is more up to date. Thanks for the patch 👍

2017-07-06 14:28 UTC, mdshuai commented on README.md
> +parameters:
@leifmadsen @rthallisey you both are right. But what I paste here is auto generated by `apb init` command, I don't change anything. I also find the file is invalid yaml. so this must be bug for apb init. you can try it.
```
(apb) [root@dhcp-140-98 dma]# apb init my_apb -p name=my_apb_param,type=string,default=foo_param,description="sample description" --async=optional --bindable --org my_organization
Initializing /tmp/dma/my_apb for an APB.
Generating playbook files
Successfully initialized project directory at: /tmp/dma/my_apb
Please run *apb prepare* inside of this directory after editing files.
(apb) [root@dhcp-140-98 dma]# cat my_apb/apb.yml 
id: b30a594e-94a8-4c6b-b4ca-29b9d465db55
name: my_apb
image: my_organization/my_apb
description: This is a sample application generated by apb init
bindable: True
async: optional
parameters: 
- name: my_apb_param
    description: sample description
    type: string
    default: foo_param
```

2017-07-06 15:04 UTC, rthallisey commented on README.md
> +parameters:
@mdshuai I misread the indent on line 113. If it's generating an invalid yaml can you open and issue for it?

2017-07-06 15:36 UTC, mdshuai commented on README.md
> +parameters:
Create issue, https://github.com/fusor/ansible-playbook-bundle/issues/65

2017-07-14 19:01 UTC, jmrodri approved these changes
Looks good to me

2017-07-24 14:34 UTC, merged